# Lecture 02 Solution

## 1. Python basic operations

some useful websites 

https://docs.scipy.org/doc/scipy/tutorial/linalg.html


https://deepnote.com/@josueglezma/Fundamentals-of-Linear-Algebra-with-Python-9c9d959b-3fdb-41af-936a-08d7a8859409

## 2. Linear Algebra basic operations

### 2.1 Vector Operations

create a vector:
$v = \begin{equation}
    \left[ \begin{array}{c}
         1  \\
         2 \\
         3
    \end{array}
    \right]
\end{equation}$

In [11]:
import numpy as np
# method with list
v1 = [1,2,3]
v1 = np.array([v1]).T #T 是进行转制
print(v1)

[[1]
 [2]
 [3]]


In [12]:
# method with numpy
v2 = np.array([[1],[2],[3]])
print(v2)

[[1]
 [2]
 [3]]


In [13]:
v = v1+v2
print(v)

[[2]
 [4]
 [6]]


In [14]:
print(3*v)

[[ 6]
 [12]
 [18]]


### 2.2 Matrix Operations

#### **Task** Create a matrix:

$M = \begin{equation}
    \left[ \begin{array}{ccc}
         1&4&7  \\
         2&5&8 \\
         3&6&9
    \end{array}
    \right]
\end{equation}$

In [15]:
# with the method of list
# TODO
import numpy as np
M = [[1,4,7],[2,5,8],[3,6,9]]
M = np.array(M)
print(M)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [16]:
# with the method of array
# TODO 
M = np.array([[1,4,7],[2,5,8],[3,6,9]])
print(M)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


#### **Task** Matrix indexing
get the result by indexing M:
$v = \begin{equation}
    \left[ \begin{array}{cc}
         4&7  \\
         5&8
    \end{array}
    \right]
\end{equation}$

In [17]:
# TODO
#从M矩阵中利用索引截取目标v
print(M[0:2,1:3])

[[4 7]
 [5 8]]


### 2.3 Many other functions for creating matrices/vectors provided Numpy

In [18]:
a = np.zeros((2,3)) # create an array with all zeros，2x3的矩阵，np.zeros自动填充为0
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
b = np.ones((1,2)) # create an array with all ones， np.ones自动填充为1
print(b)

[[1. 1.]]


In [20]:
c = np.full((2,4), 7) # create an array with constant values，自动填充常量
print(c)

[[7 7 7 7]
 [7 7 7 7]]


In [21]:
d = np.eye(3) # create a 3 by 3 identity matrix，标准矩阵
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 2.4 Multiplications

#### 2.4.1 Dot Multiplication

In [22]:
np.dot(3, 4)
#np.dot()函数主要功能有两个：向量点积和矩阵乘法。
#x.dot(y) 等价于 np.dot(x,y) ———x是m*n 矩阵 ，y是n*m矩阵，则x.dot(y) 得到m*m矩阵。


12

$M = \begin{equation}
    \left[ \begin{array}{ccc}
         1&4&7  \\
         2&5&8 \\
         3&6&9
    \end{array}
    \right]
\end{equation}$
$v = \begin{equation}
    \left[ \begin{array}{c}
         2  \\
         4 \\
         6
    \end{array}
    \right]
\end{equation}$

In [23]:
# method 1
M.dot(v)

array([[60],
       [72],
       [84]])

In [24]:
# method 2
np.dot(M,v)

array([[60],
       [72],
       [84]])

#### 2.4.2 Element-wise Multiplication

In [25]:
np.multiply(M,v)

array([[ 2,  8, 14],
       [ 8, 20, 32],
       [18, 36, 54]])

In [26]:
np.multiply(v,v)

array([[ 4],
       [16],
       [36]])

In [27]:
np.multiply(M,M)

array([[ 1, 16, 49],
       [ 4, 25, 64],
       [ 9, 36, 81]])

#### 2.4.3 Inner(dot) or Outer(cross) product

 **dot/inner product of two vectors**

In [ ]:
#dot	两数组的点积
#vdot	两向量的点积
#inner	两数组的内积
#determinant	数组的行列式
#matmul	两数组的矩阵积
#inv	求矩阵的逆
#solve	求解线性矩阵方程

In [33]:
a = np.array([1,2,3])
b = np.array([0,1,0])
np.inner(a, b)


2

In [34]:
a.ravel()

array([1, 2, 3])

In [ ]:
# In [14]: x=np.array([[1,2],[3,4]])

# flattenh函数和ravel函数在降维时默认是行序优先
In [15]: x.ravel()
Out[15]: array([1, 2, 3, 4])

# 传入'F'参数表示列序优先
In [19]: x.ravel('F')
Out[19]: array([1, 3, 2, 4])

#x.T表示x的转置
In [22]: x.T.reshape(-1)
Out[22]: array([1, 3, 2, 4])



In [35]:
#将多维的矩阵转换成一维数组
import numpy as np

# 创建一个 2x3 的数组
x = np.array([[1, 2, 3],
              [4, 5, 6]])

# 使用 .reshape(-1) 将数组展平为一维数组
flattened_array = x.reshape(-1)

print(flattened_array)


[1 2 3 4 5 6]


**inner product multidimensional example 内积**

In [20]:
# eg.1
a = np.array([[1,2,3],[4,5,6]])
b = np.array([0,1,0])
print('a:',a)
print('b:',b)
print(np.inner(a, b))

a: [[1 2 3]
 [4 5 6]]
b: [0 1 0]
[2 5]


In [38]:
# eg.2 (tensor)
a = np.arange(24).reshape((2,3,4))
b = np.arange(4)
print('a:',a)
print('b:',b)
print(np.inner(a,b))

#np.arange(24)：这部分使用 NumPy 中的 arange 函数创建了一个包含 0 到 23 这 24 个连续整数的一维数组。
#.reshape((2, 3, 4))：这部分使用 reshape 方法将一维数组重新塑造成一个具有特定形状的多维数组。在这个例子中，数组 a 被重新塑造成一个三维数组，其中第一个维度有 2 个元素，第二个维度有 3 个元素，第三个维度有 4 个元素，总共包含了 2 x 3 x 4 = 24 个元素。
#这意味着 a 现在是一个 3D 数组，它的形状是 (2, 3, 4)，表示它有 2 个 "子数组"，每个子数组有 3 行和 4 列。这种多维数组在科学计算、图像处理和机器学习等领域中非常常见，因为它们允许你有效地组织和处理多维数据。

#由于 a 有两个子数组，每个子数组的内积结果将形成结果数组的两行，而 a 的每个子数组内部有 3 行，因此结果数组的每一行将有 3 个元素。
#点乘


a: [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
b: [0 1 2 3]
[[ 14  38  62]
 [ 86 110 134]]


#扩展后的b：
#b = np.array([[[0, 1, 2, 3],
               [0, 1, 2, 3],
               [0, 1, 2, 3]],
              
              [[0, 1, 2, 3],
               [0, 1, 2, 3],
               [0, 1, 2, 3]]])


In [36]:
#广播（Broadcasting）是NumPy中一种非常有用的机制，允许你在不同形状的数组之间执行元素级操作，而无需显式复制数据以使数组具有相同形状。广播的目标是让不同形状的数组可以按元素相互操作，而不需要进行显式的形状转换。
#广播的规则如下：如果两个数组的维度（轴数）不同，将较低维度的数组扩展到较高维度的数组的形状，以使它们的维度匹配。这涉及在较低维度的数组的形状前面添加长度为1的维度。
#如果两个数组的维度匹配，或者其中一个数组的维度为1，那么它们的形状是兼容的，可以进行元素级操作。
#如果两个数组在任何维度上都不兼容，那么广播操作将失败，并引发错误。
#广播使你能够以更简洁和有效的方式执行各种元素级操作，而不必显式复制数据以匹配形状。这在处理不同形状的数组时非常方便，例如，在机器学习、图像处理和科学计算等领域。

import numpy as np

# 创建一个形状为 (3, 3) 的数组
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# 创建一个形状为 (3, ) 的数组
b = np.array([10, 20, 30])

# 使用广播将两个数组相加
result = a + b

print(result)


[[11 22 33]
 [14 25 36]
 [17 28 39]]


**outer product 外积
外积是一种操作，它将两个向量转化为一个矩阵，其中矩阵的每个元素是两个向量对应位置元素的乘积。**

In [40]:
import numpy as np

# 创建一个形状为 (5,) 的一维数组 a，所有元素都是 1
a = np.ones((5,))

# 创建一个形状为 (5,) 的一维数组 b，元素从 -2 到 2 等间隔分布
b = np.linspace(-2, 2, 5)

# 输出数组 a 和 b
print('a:', a)
print('b:', b)

# 计算数组 a 和 b 的外积
result = np.outer(a, b)

# 输出外积结果
print(result)


a: [1. 1. 1. 1. 1.]
b: [-2. -1.  0.  1.  2.]
[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]


#### 2.4.4 Matrix product of two arrays 矩阵计算

In [23]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])
c = np.array([1, 2])

In [24]:
np.matmul(a, b)

array([[4, 1],
       [2, 2]])

In [25]:
np.matmul(a,c)

array([1, 2])

# #区分inner和outer

## np.inner 的示例

np.inner 用于计算两个向量的内积（点积）。内积的结果是标量。
import numpy as np

#### 示例1: 计算两个三维向量的内积
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.inner(a, b)
print("内积结果:", result)  # 输出标量结果: 32

#### 示例2: 计算两个二维向量的内积
a = np.array([1, 2])
b = np.array([3, 4])

result = np.inner(a, b)
print("内积结果:", result)  # 输出标量结果: 11

## np.outer 的示例

np.outer 用于计算两个向量的外积。外积的结果是一个矩阵，其中每个元素都是两个向量对应位置元素的乘积。

In [42]:
import numpy as np

#### 示例1: 计算两个一维向量的外积
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
#（用1去乘以4，5，6，得到第一行结果）

result = np.outer(a, b)
print("外积结果:")
print(result)

#外积结果:
#[[ 4  5  6]
# [ 8 10 12]
# [12 15 18]]


外积结果:
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


### 2.5 Properties 属性

#### 2.5.1 Transpose 转置

In [26]:
print(M)
print(M.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
print(v)
print(v.T)

[[2]
 [4]
 [6]]
[[2 4 6]]


In [28]:
print(M.shape)
print(M.T.shape)
print(v.shape)
print(v.T.shape)

(3, 3)
(3, 3)
(3, 1)
(1, 3)


#### 2.5.2 Matrix Determinant 行列式
如果行列式的值为零，表示矩阵是奇异的（非可逆的）；如果不为零，表示矩阵是可逆的。

In [29]:
a = np.array([[1, 2], [3, 4]])
np.linalg.det(a)

-2.0000000000000004

#### 2.5.3 Matrix Inverse 逆矩阵
使用 np.linalg.inv 函数来计算它的逆矩阵

In [30]:
from numpy.linalg import inv

a = np.array([[1., 2.], [3., 4.]])
ainv = inv(a)

In [31]:
print('a:',a)
print('inv:',ainv)

a: [[1. 2.]
 [3. 4.]]
inv: [[-2.   1. ]
 [ 1.5 -0.5]]


#### 2.5.4 Eigenvalues and Eigenvectors 特征值和特征向量

In [55]:
from numpy import linalg as LA
w, v = LA.eig(np.diag((1, 2, 3)))

np.diag 函数来创建对角矩阵，并使用 LA.eig 函数来计算对角矩阵的特征值和特征向量。
特征值 w 是一个包含特征值的数组，特征向量 v 是一个包含特征向量的矩阵，其中每列是一个特征向量。

In [56]:
w

array([1., 2., 3.])

In [34]:
v

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
test2 = np.array([[1,-0.3],[-0.7,0.6]])
eia,eib = LA.eig(test2)
print(eia)
print(eib)

[1.3 0.3]
[[ 0.70710678  0.3939193 ]
 [-0.70710678  0.91914503]]


np.array([[1, -0.3], [-0.7, 0.6]]) 创建了一个2x2的矩阵 test2，它是一个任意的矩阵。
LA.eig(test2) 使用 NumPy 中的 LA.eig 函数计算了 test2 的特征值和特征向量。
eia 包含 test2 的特征值。
eib 包含 test2 的特征向量，其中每列是一个特征向量。

In [36]:
test2 = np.array([[1.5,0],[0,0.5]])
eia,eib = LA.eig(test2)
print(eia)
print(eib)

[1.5 0.5]
[[1. 0.]
 [0. 1.]]


In [63]:
import numpy as np
from numpy.linalg import eig

# 定义2x2矩阵 test
test = np.array([[0.8, -0.6], [0.4, -0.3]])

# 使用 eig 函数计算特征值和特征向量
eia, eib = eig(test)

# 打印特征值和特征向量
print("特征值:")
print(eia)
print("特征向量:")
print(eib)


特征值:
[ 5.00000000e-01 -5.55111512e-17]
特征向量:
[[0.89442719 0.6       ]
 [0.4472136  0.8       ]]


In [64]:
eia

array([ 5.00000000e-01, -5.55111512e-17])

In [65]:
eib

array([[0.89442719, 0.6       ],
       [0.4472136 , 0.8       ]])

### 2.6 Arithmetic operators including addition +, subtraction -, multiplication *, division / and exponentiation ** are applied to arrays elementwise. 算术运算符，包括加+、减-、乘法、除法/和指数*，应用于元素数组。

In [41]:
A = np.array([[3,1],[2,-1]])
B = np.array([[2,-2],[5,1]])
print(A)
print(B)

[[ 3  1]
 [ 2 -1]]
[[ 2 -2]
 [ 5  1]]


In [42]:
A * B

array([[ 6, -2],
       [10, -1]])

In [43]:
A ** 2

array([[9, 1],
       [4, 1]])

In Python 3.5+, the symbol @ computes matrix multiplication for NumPy arrays

In [44]:
A @ B

array([[11, -5],
       [-1, -5]])

Matrix powers are performed by the function numpy.linalg.matrix_power. It's a long function name and so it's convenient to import it with a shorter name:

In [45]:
from numpy.linalg import matrix_power as mpow

Compute $A^3$

In [46]:
mpow(A,3)

array([[37,  9],
       [18,  1]])

In [47]:
A @ A @ A

array([[37,  9],
       [18,  1]])

### 2.7 Others: Broadcasting

In [48]:
x = np.array([0,0.25,0.5,0.75,1.0])
y = x**2 + np.array([1,1,1,1,1])
print(y)

[1.     1.0625 1.25   1.5625 2.    ]


In [49]:
x = np.array([0,0.25,0.5,0.75,1.0])
y = x**2 + 1
print(y)

[1.     1.0625 1.25   1.5625 2.    ]


In [50]:
u = np.array([1,2,3,4])
print(u)

[1 2 3 4]


In [51]:
A = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
print(A)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]


In [52]:
result = A + u
print(result)


[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


In [51]:
x = np.array([1,23,4])
y = x.T

In [54]:
x+y

array([ 2, 46,  8])

In [53]:
import numpy as np

# 创建一个一维数组 x
x = np.array([1, 23, 4])

# 获取 x 的转置
y = x.T

# 输出结果
print("x:")
print(x)
print("y (x 的转置):")
print(y)


x:
[ 1 23  4]
y (x 的转置):
[ 1 23  4]


对于一维数组 [1, 23, 4]，它的转置仍然是它自己，因为一维数组没有行列之分。所以 [1, 23, 4] 的转置仍然是 [1, 23, 4]。